[package]
name = "rs_ws_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.17.2"
url = "2.2.2"
log = "0.4.17"
env_logger = "0.9.0"